services:
  backend:
    build: ./chicken_farm_backend
    container_name: farm-backend
    restart: always
    networks:
      - farm-network
    env_file:
      - ./chicken_farm_backend/.env
    ports:
      - "${BACKEND_PORT-4000}:4000"
  frontend:
    build:
      context: ./chicken_farm_frontend
      args:
        - NEXT_PUBLIC_CHICKEN_API_URL=http://${EC2_HOST:-localhost}:${BACKEND_PORT:-4000}/api/chickens
    environment:
      - NEXT_PUBLIC_CHICKEN_API_URL=http://${EC2_HOST:-localhost}:${BACKEND_PORT:-4000}/api/chickens
      - PORT=3232
    container_name: farm-frontend
    restart: always
    env_file:
      - ./chicken_farm_frontend/.env
    networks:
      - farm-network
    ports:
      - "3232:3232"
    depends_on:
      - backend

networks:
  farm-network:
    driver: bridge
