services:
  backend:
    build: ./chicken_farm_backend
    container_name: farm-backend
    restart: always
    networks:
      - farm-network
    env_file:
      - ./chicken_farm_backend/.env
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./chicken_farm_frontend
      args:
        - NEXT_PUBLIC_CHICKEN_API_URL=http://localhost:4000
    container_name: farm-frontend
    restart: always
    env_file:
      - ./chicken_farm_frontend/.env
    networks:
      - farm-network
    ports:
      - "3232:3232"
    depends_on:
      - backend

networks:
  farm-network:
    driver: bridge
