name: build-and-lint

#trigger the workflow on push or pull request to main branch
# also trigger on pus to dev branch
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

      #run the workflow on ubuntu-latest
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: install backend dependencies
        working-directory: chicken_farm_backend
        run: npm ci
      - name: lint backend
        working-directory: chicken_farm_backend
        run: npm run lint -- --max-warnings=0

      - name: install frontend dependencies
        working-directory: chicken_farm_frontend
        run: npm ci
      - name: lint frontend
        working-directory: chicken_farm_frontend
        run: npm run lint -- --max-warnings=0

      #Remember to set the work directory and instruct docker to find the Docker file in the current path with a . at the end
      - name: build backend image
      working-directory: ./chicken_farm_backend
      run: docker build -t chicken-farm-backend .
      
      #Remember to set the work directory and instruct docker to find the Docker file in the current path with a . at the end
      - name: build frontend image
      working-directory: ./chicken_farm_frontend
      run: docker build -t chicken-farm-frontend .
